### PR TITLE
use psr-4 autoloading

### PR DESCRIPTION
**Pull request by smoench**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👍

**Comment by mvriel** [comment]
Can't merge on my phone due to the Travis failure. I know that is resolved when master is rebased in but can't do that on the phone. Will merge tomorrow

**Comment by smoench** [comment]
@mvriel I did a rebase :-)

**Comment by GrahamCampbell** [comment]
👍

**Comment by jaapio** [comment]
Thanks

**Pull request merged**
