### PR TITLE
Update Node.php

### PR DESCRIPTION
**Pull request by Julyanvdham**
This edit makes sure that backslashes are not removed when the chart is made.

### CODE REVIEW

**Comment by jaapio** [comment]
Could you please provide a testcase that covers this behavior?

**Comment by ashnazg** [comment]
Judging from cc3732152f66d831e148105bff565b63fef7217b, this backslashing is intentional.

**Comment by jaapio** [comment]
I don't know if it is intentional. @mvriel could know the answer but it seems to be long time ago that this was introduced. Since this PR doesn't change any tests and does break tests if seems to be invalid to me. Tests are leading for me when in doubt.

**Comment by ashnazg** [comment]
See `AttributeTest::testToStringWithSpecials()`... `Double backslashes should stay the same` is one of the assertion messages.  I'm fairly convinced by now that the existing behavior is intentional and correct.

**Pull request closed without merging**
