### PR TITLE
Issue #33: Fix directed edges

### PR DESCRIPTION
**Pull request by drupol**
This PR:

* [x] Fix bug #33 
* [x] Adds 2 interfaces.
* [x] Adds 1 trait.
* [ ] Update code style.
* [ ] Adds `.editorconfig` configuration file.
* [ ] Adds `.gitattributes` file.
* [ ] Use Grumphp for pre-commit checks.

### CODE REVIEW

**Comment by jaapio** [comment]
Thanks for this PR,

You are introducing quite a lot of other things in this PR than just a fix for this issue you found. Please remove those. And make this a clean PR to fix the issue. Any additional changes can be discussed but should not be in this pr. 

It is perfectly ok if you are using tools to improve your own code base, but I don't want them in this repo right now. If we want to introduce Grumphp for example I want to use it organisation wide and define how to introduce it. Not just in a single repo, without any additional that is organisation wide used.

**Comment by drupol** [comment]
Allrighty, removed all the unrelated stuff.

**Comment by drupol** [comment]
Waiting for your feedback @jaapio .

**Comment by dereuromark** [comment]
Is there any chance this is moving forward - and changes into master?

**Pull request closed without merging**
