### PR TITLE
real getters and setters for attributes

### PR DESCRIPTION
**Pull request by smoench**
I really would like to use this library for https://github.com/sensiolabs-de/deptrac. But I have some trouble with the magic attributes setter and getter. So I would like to contribute real getters and setters for attributes.

~~Besides I did some more improvements. If there is any interest in those patches I would cherry-pick the commits and create PRs for each of them.~~

### CODE REVIEW

**Comment by jaapio** [comment]
I never looked at this library before. But most patches look sane to me. I have to look at them in detail before I can provide any useful comments. But in general I think it is good to keep this up to date. :+1:

**Comment by jaapio** [comment]
Could you please rebase this PR and add extra tests to fix the coverage drop?

**Comment by smoench** [comment]
Coverage is back to 100%

**Comment by jaapio** [comment]
Thanks, I will check if we are ready for a new release :-)

**Comment by smoench** [comment]
@jaapio Is there anything left for a new release or can I help somehow?

**Comment by jaapio** [comment]
Still need to check, I have way too many things to do :smile:

**Pull request merged**
